### ISSUE TITLE
Missing param represents object handle

### ISSUE THREAD

**Issue by harrison314** [Pkcs11Interop/Pkcs11Interop#220] opened 2023-02-15 06:56 UTC
In `IMechanismParamsFactory` missing method for create `CK_OBJECT_HANDLE` as mechanism parameter.

For example, it is used from `CKM_CONCATENATE_BASE_AND_KEY` - <https://www.cryptsoft.com/pkcs11doc/v220/group__SEC__12__34__3__CONCATENATION__OF__A__BASE__KEY__AND__ANOTHER__KEY.html#CKM_CONCATENATE_BASE_AND_KEY>.

**Comment by jariq** [comment] 2024-10-04 23:04
Closing as a duplicate of #145.

**Closed by jariq** 2024-10-04 23:04 UTC
