### ISSUE TITLE
Xamarin.Android Error

### ISSUE THREAD

**Issue by kegfire** [Pkcs11Interop/Pkcs11Interop#96] opened 2018-12-20 14:23 UTC
Net.Standard 2.0
Android Project
Device: Xiaomi Mi5s Android 7
Using librtpkcs11ecp.so 

I'm trying to create object Pkcs11 and when invoking 

```
NativeULong rv = _delegates.C_Initialize(initArgs);
```

I get error:

```
12-20 16:24:14.978 E/mono-rt ( 3070):   at <unknown> <0xffffffff>
12-20 16:24:14.978 E/mono-rt ( 3070):   at (wrapper managed-to-native) object.wrapper_native_0x32a50000 (Net.Pkcs11Interop.LowLevelAPI41.CK_C_INITIALIZE_ARGS) <0x00037>
12-20 16:24:14.978 E/mono-rt ( 3070):   at Net.Pkcs11Interop.LowLevelAPI41.Pkcs11.C_Initialize (Net.Pkcs11Interop.LowLevelAPI41.CK_C_INITIALIZE_ARGS) [0x0001c] in C:\git\Pkcs11Interop\src\Pkcs11Interop\Pkcs11Interop\LowLevelAPI41\Pkcs11.cs:116
12-20 16:24:14.978 E/mono-rt ( 3070):   at Net.Pkcs11Interop.HighLevelAPI41.Pkcs11.Initialize (Net.Pkcs11Interop.Common.AppType) [0x00039] in C:\git\Pkcs11Interop\src\Pkcs11Interop\Pkcs11Interop\HighLevelAPI41\Pkcs11.cs:177
12-20 16:24:14.978 E/mono-rt ( 3070):   at Net.Pkcs11Interop.HighLevelAPI41.Pkcs11..ctor (Net.Pkcs11Interop.HighLevelAPI.Pkcs11Factories,string,Net.Pkcs11Interop.Common.AppType) [0x0005a] in C:\git\Pkcs11Interop\src\Pkcs11Interop\Pkcs11Interop\HighLevelAPI41\Pkcs11.cs:116
12-20 16:24:14.978 E/mono-rt ( 3070):   at FirstModule.ViewModel.FirstPageViewModel.Test () [0x00071] in C:\...\XamarinFormsLab\FirstModule\ViewModel\FirstPageViewModel.cs:55
12-20 16:24:14.978 E/mono-rt ( 3070):   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x0004f] in <fe08c003e91342eb83df1ca48302ddbb>:0
12-20 16:24:14.978 E/mono-rt ( 3070):   at <unknown> <0xffffffff>
12-20 16:24:14.979 E/mono-rt ( 3070):   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0x00043>
12-20 16:24:14.979 E/mono-rt ( 3070):   at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x00041] in <fe08c003e91342eb83df1ca48302ddbb>:0
12-20 16:24:14.979 E/mono-rt ( 3070):   at System.Reflection.MethodBase.Invoke (object,object[]) [0x00006] in <fe08c003e91342eb83df1ca48302ddbb>:0
12-20 16:24:14.979 E/mono-rt ( 3070):   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute () [0x0003e] in C:\Users\lbugn\Documents\MVVMLight\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\Helpers\WeakAction.cs:343
12-20 16:24:14.979 E/mono-rt ( 3070):   at GalaSoft.MvvmLight.Command.RelayCommand.Execute (object) [0x0002b] in C:\Users\lbugn\Documents\MVVMLight\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\Command\RelayCommand.cs:228
12-20 16:24:14.979 E/mono-rt ( 3070):   at Xamarin.Forms.Button.SendClicked () [0x00008] in D:\a\1\s\Xamarin.Forms.Core\Button.cs:150
12-20 16:24:14.979 E/mono-rt ( 3070):   at Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer/ButtonClickListener.OnClick (Android.Views.View) [0x0000b] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs:329
12-20 16:24:14.979 E/mono-rt ( 3070):   at Android.Views.View/IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (intptr,intptr,intptr) [0x00013] in <ad2f15102b3a4d36b40e9b0cbc11c376>:0
12-20 16:24:14.980 E/mono-rt ( 3070):   at (wrapper dynamic-method) object.26 (intptr,intptr,intptr) [0x00017] in <fe08c003e91342eb83df1ca48302ddbb>:0
12-20 16:24:14.980 E/mono-rt ( 3070):   at (wrapper native-to-managed) object.26 (intptr,intptr,intptr) [0x00022] in <fe08c003e91342eb83df1ca48302ddbb>:0
```

Could you help me?

**Comment by jariq** [comment] 2018-12-20 17:03
Could you please test our sample Android application [Pkcs11Interop.Android.Tests](https://github.com/Pkcs11Interop/Pkcs11Interop/tree/4.0.0/src/Pkcs11Interop.Android) on your device?

**Comment by kegfire** [comment] 2018-12-21 07:15
142 passed, 106 failed, 198 inconclusive.
Before running the tests, i changed target patform to Oreo 8.1  in Pkcs11Interop and Pkcs11Interop.Mock.
In failed tests app couldn't find "libpkcs11-mock.so" file.
May need to specify a directory here (method GetPkcs11MockLibraryPath())?
`#if __ANDROID__
            return @"libpkcs11-mock.so";`
Example failed test result
![photo_2018-12-21_10-10-30](https://user-images.githubusercontent.com/20456708/50329572-e583ad00-0508-11e9-931c-c3104eab7789.jpg)

**Comment by kegfire** [comment] 2018-12-21 07:52
For experiment I made copy arm64-v8 vesion library into project root directory. In file properies I picked "Embedded Resource".
Then in Settings.cs I replaced
`return @"libpkcs11-mock.so`
by
`	var libPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Net.Pkcs11Interop.Tests.libpkcs11-mock.so");
	        if (!File.Exists(libPath))
	        {
			using (var resource = typeof(Settings).Assembly.GetManifestResourceStream("Net.Pkcs11Interop.Tests.libpkcs11-mock.so"))
				{
					using (var file = new FileStream(libPath, FileMode.Create, FileAccess.Write))
					{
						resource?.CopyTo(file);
					}
				}
			}
	        return libPath;`
After that I got the following results:
 248 Passed, 198 inconclusive

**Comment by jariq** [comment] 2018-12-21 19:23
Great. That means Pkcs11Interop with `pkcs11-mock.so` is working on your device. As a next step you can try to replace `pkcs11-mock.so` with your unmanaged library `librtpkcs11ecp.so` and test again. You can also consider excluding all tests from `Pkcs11Interop.Android.Tests` project and leaving just [`_02_GetInfoTest.cs`](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/4.0.0/src/Pkcs11Interop/Pkcs11InteropTests/HighLevelAPI/_02_GetInfoTest.cs) so your smartcard doesn't get blocked by more advanced tests.

**Comment by kegfire** [comment] 2018-12-25 07:48
I changed supported architecture in Tests project to armeabi;armeabi-v7a because 'librtpkcs11ecp.so' is 32bit library. Uncheck "Use Shared Runtime"  because if its checked - application doesn't work (https://github.com/xamarin/xamarin-android/issues/1404).
Now I have an error:
"Unable to load library. Error detail: dlopen failed: file offset for the library "/data/user/0/Pkcs11Interop.Android.Tests.Pkcs11Interop.Android.Tests/files/librtpkcs11ecp.so" >= file size: 0 >= 0"
I dont know why NativeMethods.dlopen(fileName, flags) returns 0 because in my project same library works fine in this method.
Could you try run tests with this lib? I attached file in archive.
[librtpkcs11ecp.zip](https://github.com/Pkcs11Interop/Pkcs11Interop/files/2708338/librtpkcs11ecp.zip)

**Comment by kegfire** [comment] 2019-01-09 06:05
yes

**Comment by jariq** [comment] 2019-01-15 22:31
@kegfire it seems that your device is having trouble finding/accessing/reading PKCS#11 library. First the default implementation of `GetPkcs11MockLibraryPath()` method did not work for you with `libpkcs11-mock.so` and now with `librtpkcs11ecp.so` you seem to be getting this "strange" error:

```
Unable to load library. Error detail: dlopen failed: file offset for the library "/data/user/0/Pkcs11Interop.Android.Tests.Pkcs11Interop.Android.Tests/files/librtpkcs11ecp.so" >= file size: 0 >= 0
```

This IMO too indicates problem with finding/accessing/reading PKCS#11 library. It might be issue with permissions, file-system, Xiaomi's customization etc. I'm not quite sure so I'm trying to replicate your issue. Here's what I've done so far:

1. I took `Pkcs11Interop.Android` from current master branch and switched all projects to `Android 8.1 (Oreo)` target framework.
2. I've tested  `Pkcs11Interop.Android.Tests` application with `libpkcs11-mock.so` on emulator with following settings `Base Device: Nexus 5X`, `Processor: x86`, `OS: Oreo 8.1 - API 27` and it worked fine.
3. I wanted to test with `Processor: armeabi-v7a` but that emulator refuses to run on my PC.

Here's what I'm planning to test next:

1. Get some physical `armeabi-v7a` device with `Android 8.1 (Oreo)` and test on it with `libpkcs11-mock.so`.
2. If previous test is successful I'll test on the same device with `librtpkcs11ecp.so` from Rutoken SDK.

Sadly I currently don't have much free time left and I also don't have `armeabi-v7a` device with `Android 8.1 (Oreo)`. But I'm trying to do my best and I'll surely update this issue once there's anything new to add.

So let's sum it up: Your device seems to be having some issues when it comes to **finding/accessing/reading unmanaged libraries** and I'm unable to replicate these issues in emulator. They also never occurred on any other device I tested. My suggestion for you is to test with other devices, other OS versions etc. IMO it's not Pkcs11Interop that is failing here, but system's `dlopen()` function and it's ability to access unmanaged libraries.

**Comment by jariq** [comment] 2019-01-15 22:56
@Neraverin thanks for participating here. Could you please clarify what is the target architecture of PKCS#11 library `sdk-211118-266079\mobile\android\pkcs11\lib\librtpkcs11ecp.so` and what version of NDK was it built with?

It is the library @kegfire is using and I'm little confused by it because it's size `2.598.100 B` does not match any other library placed in `sdk-211118-266079\pkcs11\lib\` folder. Maybe its architecture does not match architecture of the device @kegfire is using?

BTW I find it rather unusual that there's just a single library in `android` folder. Let's take a look at  [pkcs11-mock](https://github.com/Pkcs11Interop/pkcs11-mock) for example. When you build it for Android you get following output:

```
├───arm64-v8a
│       libpkcs11-mock.so
├───armeabi
│       libpkcs11-mock.so
├───armeabi-v7a
│       libpkcs11-mock.so
├───mips
│       libpkcs11-mock.so
├───mips64
│       libpkcs11-mock.so
├───x86
│       libpkcs11-mock.so
└───x86_64
        libpkcs11-mock.so
```

Output folder contains libraries for all architectures supported by [NDK](https://developer.android.com/ndk/) so application developer can choose the correct one or include all of them. More details are available at https://docs.microsoft.com/en-us/xamarin/android/platform/native-libraries

**Comment by kegfire** [comment] 2019-01-18 12:04
@jariq  I started from the beginning. Now your tests works correctly without any manipulations with files.
And librtpkcs11ecp.so works in your test project too.
**But** Pkcs11Factory is not created.
I have an error in method  NativeULong rv = _delegates.C_Initialize(initArgs);
Please read this stacktrace. Thanks a lot!
[ErrorDescription.txt](https://github.com/Pkcs11Interop/Pkcs11Interop/files/2772837/ErrorDescription.txt)

**Comment by jariq** [comment] 2019-01-21 00:07
> And librtpkcs11ecp.so works in your test project too. But Pkcs11Factory is not created.

I'm little confused because first sentence says it does work and then second sentence says it does not. Could you please describe in more detail what is working and what not?

**Comment by kegfire** [comment] 2019-01-21 06:15
Library loaded ( _p11 = new LowLevelAPI41.Pkcs11(_libraryPath)), but method _p11.C_Initialize(initArgs) didn't execute.

**Comment by jariq** [comment] 2019-01-21 23:16
I see no error in attached `ErrorDescription.txt` file that would indicate a problem with `C_Initialize`.
Are you getting also an exception that you forgot to post here?

**Comment by kegfire** [comment] 2019-01-23 06:44
Now after installing "Control Panel Rutoken" app tests doesn't crash. but i have problem with permissions. Maybe you have seen these errors before.
"android.permission.USB_PERMISSION" and "android.permission.READ_EXTERNAL_STORAGE" doesn't helps. 
It happening when `C_Initialize` method executing.

01-23 09:27:10.535 W/p.Android.Tests(13483): type=1400 audit(0.0:4758): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:12.455 I/chatty  (13483): uid=10276(u0_a276) Pkcs11Interop.Android.Tests.Pkcs11Interop.Android.Tests identical 4 lines
01-23 09:27:13.475 W/p.Android.Tests(13483): type=1400 audit(0.0:4763): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:14.495 W/p.Android.Tests(13483): type=1400 audit(0.0:4764): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/context.cpp:282: error in tryConnect: Permission denied
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:33: error in SCardEstablishContext: Permission denied
01-23 09:27:20.785 I/chatty  (13483): uid=10276(u0_a276) Pkcs11Interop.Android.Tests.Pkcs11Interop.Android.Tests identical 7 lines
01-23 09:27:21.045 W/p.Android.Tests(13483): type=1400 audit(0.0:4772): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:21.555 W/p.Android.Tests(13483): type=1400 audit(0.0:4773): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:23.615 W/p.Android.Tests(13483): type=1400 audit(0.0:4775): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:24.635 W/p.Android.Tests(13483): type=1400 audit(0.0:4776): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:25.655 W/p.Android.Tests(13483): type=1400 audit(0.0:4777): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:26.685 W/p.Android.Tests(13483): type=1400 audit(0.0:4778): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:27.705 W/p.Android.Tests(13483): type=1400 audit(0.0:4779): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:28.735 I/chatty  (13483): uid=10276(u0_a276) Pkcs11Interop.Android.Tests.Pkcs11Interop.Android.Tests identical 1 line
01-23 09:27:29.765 W/p.Android.Tests(13483): type=1400 audit(0.0:4781): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/context.cpp:282: error in tryConnect: Permission denied
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:33: error in SCardEstablishContext: Permission denied
01-23 09:27:30.785 W/p.Android.Tests(13483): type=1400 audit(0.0:4782): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:33.735 I/chatty  (13483): uid=10276(u0_a276) Pkcs11Interop.Android.Tests.Pkcs11Interop.Android.Tests identical 5 lines
01-23 09:27:34.755 W/p.Android.Tests(13483): type=1400 audit(0.0:4788): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
01-23 09:27:35.785 W/p.Android.Tests(13483): type=1400 audit(0.0:4789): avc: denied { connectto } for path=0072752E7275746F6B656E2E736572766963652E736F636B6574 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app_25:s0:c512,c768 tclass=unix_stream_socket permissive=0
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/context.cpp:282: error in tryConnect: Permission denied
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:33: error in SCardEstablishContext: Permission denied
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/context.cpp:282: error in tryConnect: Permission denied

/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:33: error in SCardEstablishContext: Permission denied
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003

/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error 
code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003
/home/jenkins/newjenkins/workspace/pcsc-android-lib/3344cef5/pcsc/winscard.cpp:88: error in SCardConnectA: Error code: 0x80100003

**Comment by Neraverin** [comment] 2019-01-23 06:52
@jariq I think you can close the issue. Your library works great with librtpkcs11.so, which is confirmed by tests. The remaining problems are more likely problems in Xamarin project settings or in our smart card service for android.

**Closed** 2019-01-24 21:16 UTC
